# Generated by Django 5.2.8 on 2025-11-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0006_scannerprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="stations_online",
        ),
        migrations.AddField(
            model_name="line",
            name="stations",
            field=models.ManyToManyField(to="ticket.station"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("IN_USE", "In Use"),
                    ("EXPIRED", "Expired"),
                    ("USED", "Used"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
