# Generated by Django 5.2.8 on 2025-11-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='ticket.line'),
            preserve_default=False,
        ),
    ]
