# Generated by Django 5.2.8 on 2026-01-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="scan_in",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="scan_out",
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name="FootFall",
        ),
    ]
