# Generated by Django 5.2.8 on 2025-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="line",
            name="stations",
            field=models.ManyToManyField(
                related_name="lines",
                through="ticket.ThroughTable",
                through_fields=("line", "station"),
                to="ticket.station",
            ),
        ),
        migrations.AlterField(
            model_name="throughtable",
            name="order",
            field=models.PositiveIntegerField(),
        ),
    ]
