# Generated by Django 5.2.8 on 2026-01-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_ticket_scan_in_ticket_scan_out_delete_footfall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("IN_USE", "In Use"),
                    ("EXPIRED", "Expired"),
                    ("USED", "Used"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
