# Generated by Django 5.2.8 on 2025-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_station_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='line',
        ),
        migrations.AddField(
            model_name='line',
            name='stations_online',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
