# Generated by Django 5.2.8 on 2025-11-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_otp_alter_line_stations_alter_throughtable_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootFall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("into", models.PositiveIntegerField(default=0)),
                ("out", models.PositiveIntegerField(default=0)),
                ("date", models.DateField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ticket.station"
                    ),
                ),
            ],
        ),
    ]
