# Generated by Django 5.2.8 on 2025-11-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_station_line_line_stations_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uid',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
