# Generated by Django 5.2.8 on 2026-02-08 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_alter_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="uid",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
