# Generated by Django 5.2.8 on 2025-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_USE', 'In Use'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10),
        ),
    ]
